name: QqGroupChatSync
version: '${project.version}'
main: cn.paper_card.qq_group_chat_sync.ThePlugin
api-version: '1.20'
folia-supported: true
author: Paper99

depends:
  PaperClient

commands:
  qq-group-chat-sync:
    permission: qq-group-chat-sync.command
    aliases: [ qgcs ]

permissions:
  qq-group-chat-sync.command:
    default: op
